In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("ahmedabbas757/coffee-sales")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\Naomi\.cache\kagglehub\datasets\ahmedabbas757\coffee-sales\versions\1

In [4]:
import pandas as pd

def time_of_day(x):
  if x < 12:
    return 'Morning'
  elif x < 17:
    return 'Afternoon'
  else:
    return 'Evening'

def clean_info(x):
  sizes = [' Rg', ' Lg', 'Sm']
  return x.replace(sizes[0], '').replace(sizes[1], '').replace(sizes[2], '')


data = pd.read_excel(path + "/Coffee Shop Sales.xlsx")
data['total'] = data['transaction_qty'] * data['unit_price']
data['weekday'] = data['transaction_date'].dt.day_name()
data['month'] = data['transaction_date'].dt.month_name()
data['time_of_day'] = data['transaction_time'].apply(lambda x: time_of_day(x.hour))
data['nday'] = data['transaction_date'].dt.day

data = data.drop(['transaction_id','store_id', 'product_id'], axis=1)
data['product'] = data['product_detail'].apply(lambda x: clean_info(x))
data

,transaction_date,transaction_time,transaction_qty,store_location,unit_price,product_category,product_type,product_detail,total,weekday,month,time_of_day,nday,product
0,2023-01-01,07:06:11,2,Lower Manhattan,3.00,Coffee,Gourmet brewed coffee,Ethiopia Rg,6.00,Sunday,January,Morning,1,Ethiopia
1,2023-01-01,07:08:56,2,Lower Manhattan,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.20,Sunday,January,Morning,1,Spicy Eye Opener Chai
2,2023-01-01,07:14:04,2,Lower Manhattan,4.50,Drinking Chocolate,Hot chocolate,Dark chocolate Lg,9.00,Sunday,January,Morning,1,Dark chocolate
3,2023-01-01,07:20:24,1,Lower Manhattan,2.00,Coffee,Drip coffee,Our Old Time Diner Blend Sm,2.00,Sunday,January,Morning,1,Our Old Time Diner Blend
4,2023-01-01,07:22:41,2,Lower Manhattan,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.20,Sunday,January,Morning,1,Spicy Eye Opener Chai
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149111,2023-06-30,20:18:41,2,Hell's Kitchen,2.50,Tea,Brewed herbal tea,Peppermint Rg,5.00,Friday,June,Evening,30,Peppermint
149112,2023-06-30,20:25:10,2,Hell's Kitchen,3.00,Tea,Brewed Black tea,English Breakfast Lg,6.00,Friday,June,Evening,30,English Breakfast
149113,2023-06-30,20:31:34,1,Hell's Kitchen,3.00,Tea,Brewed herbal tea,Peppermint Lg,3.00,Friday,June,Evening,30,Peppermint
149114,2023-06-30,20:57:19,1,Hell's Kitchen,3.75,Coffee,Barista Espresso,Cappuccino,3.75,Friday,June,Evening,30,Cappuccino
149115,2023-06-30,20:57:19,2,Hell's Kitchen,0.80,Flavours,Regular syrup,Hazelnut syrup,1.60,Friday,June,Evening,30,Hazelnut syrup

In [5]:
data['product_detail'].apply(lambda x: clean_info(x))

0                          Ethiopia
1             Spicy Eye Opener Chai
2                    Dark chocolate
3         Our Old Time Diner Blend
4             Spicy Eye Opener Chai
                    ...
149111                   Peppermint
149112            English Breakfast
149113                   Peppermint
149114                   Cappuccino
149115               Hazelnut syrup
Name: product_detail, Length: 149116, dtype: object

In [6]:
data['transaction_time'].iloc[0]

datetime.time(7, 6, 11)

In [7]:
data.groupby('store_location').count()

,transaction_date,transaction_time,transaction_qty,unit_price,product_category,product_type,product_detail,total,weekday,month,time_of_day,nday,product
store_location,,,,,,,,,,,,,
Astoria,50599,50599,50599,50599,50599,50599,50599,50599,50599,50599,50599,50599,50599
Hell's Kitchen,50735,50735,50735,50735,50735,50735,50735,50735,50735,50735,50735,50735,50735
Lower Manhattan,47782,47782,47782,47782,47782,47782,47782,47782,47782,47782,47782,47782,47782

In [8]:
data.groupby('product_category').count()

,transaction_date,transaction_time,transaction_qty,store_location,unit_price,product_type,product_detail,total,weekday,month,time_of_day,nday,product
product_category,,,,,,,,,,,,,
Bakery,22796,22796,22796,22796,22796,22796,22796,22796,22796,22796,22796,22796,22796
Branded,747,747,747,747,747,747,747,747,747,747,747,747,747
Coffee,58416,58416,58416,58416,58416,58416,58416,58416,58416,58416,58416,58416,58416
Coffee beans,1753,1753,1753,1753,1753,1753,1753,1753,1753,1753,1753,1753,1753
Drinking Chocolate,11468,11468,11468,11468,11468,11468,11468,11468,11468,11468,11468,11468,11468
Flavours,6790,6790,6790,6790,6790,6790,6790,6790,6790,6790,6790,6790,6790
Loose Tea,1210,1210,1210,1210,1210,1210,1210,1210,1210,1210,1210,1210,1210
Packaged Chocolate,487,487,487,487,487,487,487,487,487,487,487,487,487
Tea,45449,45449,45449,45449,45449,45449,45449,45449,45449,45449,45449,45449,45449

In [9]:
data.groupby('product_type').count()

,transaction_date,transaction_time,transaction_qty,store_location,unit_price,product_category,product_detail,total,weekday,month,time_of_day,nday,product
product_type,,,,,,,,,,,,,
Barista Espresso,16403,16403,16403,16403,16403,16403,16403,16403,16403,16403,16403,16403,16403
Biscotti,5711,5711,5711,5711,5711,5711,5711,5711,5711,5711,5711,5711,5711
Black tea,303,303,303,303,303,303,303,303,303,303,303,303,303
Brewed Black tea,11350,11350,11350,11350,11350,11350,11350,11350,11350,11350,11350,11350,11350
Brewed Chai tea,17183,17183,17183,17183,17183,17183,17183,17183,17183,17183,17183,17183,17183
Brewed Green tea,5671,5671,5671,5671,5671,5671,5671,5671,5671,5671,5671,5671,5671
Brewed herbal tea,11245,11245,11245,11245,11245,11245,11245,11245,11245,11245,11245,11245,11245
Chai tea,443,443,443,443,443,443,443,443,443,443,443,443,443
Clothing,221,221,221,221,221,221,221,221,221,221,221,221,221
Drinking Chocolate,266,266,266,266,266,266,266,266,266,266,266,266,266
Drip coffee,8477,8477,8477,8477,8477,8477,8477,8477,8477,8477,8477,8477,8477
Espresso Beans,319,319,319,319,319,319,319,319,319,319,319,319,319
Gourmet Beans,366,366,366,366,366,366,366,366,366,366,366,366,366
Gourmet brewed coffee,16912,16912,16912,16912,16912,16912,16912,16912,16912,16912,16912,16912,16912
Green beans,134,134,134,134,134,134,134,134,134,134,134,134,134
Green tea,159,159,159,159,159,159,159,159,159,159,159,159,159
Herbal tea,305,305,305,305,305,305,305,305,305,305,305,305,305
Hot chocolate,11468,11468,11468,11468,11468,11468,11468,11468,11468,11468,11468,11468,11468
House blend Beans,183,183,183,183,183,183,183,183,183,183,183,183,183
Housewares,526,526,526,526,526,526,526,526,526,526,526,526,526
Organic Beans,415,415,415,415,415,415,415,415,415,415,415,415,415
Organic Chocolate,221,221,221,221,221,221,221,221,221,221,221,221,221
Organic brewed coffee,8489,8489,8489,8489,8489,8489,8489,8489,8489,8489,8489,8489,8489
Pastry,6912,6912,6912,6912,6912,6912,6912,6912,6912,6912,6912,6912,6912
Premium Beans,336,336,336,336,336,336,336,336,336,336,336,336,336
Premium brewed coffee,8135,8135,8135,8135,8135,8135,8135,8135,8135,8135,8135,8135,8135
Regular syrup,4979,4979,4979,4979,4979,4979,4979,4979,4979,4979,4979,4979,4979
Scone,10173,10173,10173,10173,10173,10173,10173,10173,10173,10173,10173,10173,10173
Sugar free syrup,1811,1811,1811,1811,1811,1811,1811,1811,1811,1811,1811,1811,1811

In [10]:
data.groupby('product_detail').count()

,transaction_date,transaction_time,transaction_qty,store_location,unit_price,product_category,product_type,total,weekday,month,time_of_day,nday,product
product_detail,,,,,,,,,,,,,
Almond Croissant,1903,1903,1903,1903,1903,1903,1903,1903,1903,1903,1903,1903,1903
Brazilian - Organic,209,209,209,209,209,209,209,209,209,209,209,209,209
Brazilian Lg,2771,2771,2771,2771,2771,2771,2771,2771,2771,2771,2771,2771,2771
Brazilian Rg,2904,2904,2904,2904,2904,2904,2904,2904,2904,2904,2904,2904,2904
Brazilian Sm,2814,2814,2814,2814,2814,2814,2814,2814,2814,2814,2814,2814,2814
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sustainably Grown Organic Lg,2961,2961,2961,2961,2961,2961,2961,2961,2961,2961,2961,2961,2961
Sustainably Grown Organic Rg,2842,2842,2842,2842,2842,2842,2842,2842,2842,2842,2842,2842,2842
Traditional Blend Chai,153,153,153,153,153,153,153,153,153,153,153,153,153
Traditional Blend Chai Lg,2716,2716,2716,2716,2716,2716,2716,2716,2716,2716,2716,2716,2716
Traditional Blend Chai Rg,2955,2955,2955,2955,2955,2955,2955,2955,2955,2955,2955,2955,2955

In [11]:
data.columns

Index(['transaction_date', 'transaction_time', 'transaction_qty',
       'store_location', 'unit_price', 'product_category', 'product_type',
       'product_detail', 'total', 'weekday', 'month', 'time_of_day', 'nday',
       'product'],
      dtype='object')

In [12]:
# Predecir top 5 productos
data_dummies = pd.get_dummies(data, columns=['product_category', 'product_type', 'product_detail', 'weekday', 'month', 'time_of_day'])
data_daily = data_dummies.groupby('transaction_date')
data_daily.sum().reset_index()
data_train = data_daily[data_dummies['month_June'] == 0]
data_test = data_daily[data_dummies['month_June'] == 1]

X = data_train.drop(['total','transaction_time','store_location','nday','product_detail'], axis=1)
ventaTotal = data_train['total']
X_test = data_test.drop(['total','transaction_date','transaction_time','store_location','nday'], axis=1)
ventaTotal_test = data_test['total']

TypeError: unsupported operand type(s) for +: 'datetime.time' and 'datetime.time'

In [ ]:
from sklearn.linear_model import LinearRegression
modelo_venta = LinearRegression()
modelo_venta.fit(X, ventaTotal)

ValueError: could not convert string to float: 'Ethiopia'

In [ ]:
ventaTotal_pred = modelo_venta.predict(X_test)

In [ ]:
ventaTotal_pred
data_test['nday'].values

In [ ]:
import matplotlib.pyplot as plt
plt.plot(data_test['nday'].values, ventaTotal_pred, marker = "o") #Dibuja una línea uniendo los puntos (x,y)
plt.plot(data_test['nday'].values, ventaTotal_test, marker = "x")

plt.show()